name: metadatamaps
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - comm=0.2.2
  - debugpy=1.8.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.28.0
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=19.1.2
  - libedit=3.1.20191231
  - libexpat=2.6.3
  - libffi=3.4.2
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - libsqlite=3.46.1
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.13.0
  - python_abi=3.13
  - pyzmq=26.2.0
  - readline=8.2
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - pip:
      - bleach==6.1.0
      - bokeh==3.5.2
      - cartopy==0.24.1
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - colorcet==3.1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - et-xmlfile==1.1.0
      - fonttools==4.54.1
      - geopandas==1.0.1
      - geoviews==1.13.0
      - holoviews==1.19.1
      - hvplot==0.11.1
      - idna==3.10
      - ipywidgets==8.1.5
      - jinja2==3.1.4
      - jupyter-bokeh==4.0.5
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - linkify-it-py==2.0.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.1
      - matplotlib==3.9.2
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - numpy==2.1.2
      - openpyxl==3.1.5
      - pandas==2.2.3
      - panel==1.5.2
      - param==2.1.1
      - pillow==11.0.0
      - pyogrio==0.10.0
      - pyparsing==3.2.0
      - pyproj==3.7.0
      - pyshp==2.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyviz-comms==3.0.3
      - pyyaml==6.0.2
      - requests==2.32.3
      - shapely==2.0.6
      - tqdm==4.66.5
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - urllib3==2.2.3
      - webencodings==0.5.1
      - widgetsnbextension==4.0.13
      - xyzservices==2024.9.0
