name: Deploy website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Miniconda (to use Conda in GitHub Actions)
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: metadatamaps  
          environment-file: environment.yml  
          auto-activate-base: false  

      - name: Run Python script
        run: |
          conda activate metadatamaps
          python drone_metadata_map.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output